# Generated by Django 4.2.14 on 2024-11-25 05:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='published_date',
            field=models.DateField(default=datetime.datetime(2024, 11, 25, 11, 12, 23, 246868)),
        ),
    ]
