# Generated by Django 4.2.14 on 2024-11-29 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='last_date',
            field=models.DateField(auto_now=True),
        ),
    ]
