# Generated by Django 4.2.14 on 2024-11-29 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_last_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='last_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
