# Generated by Django 4.2.14 on 2024-12-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blog_istemp'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commented_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
