# Generated by Django 4.2.14 on 2024-12-18 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_comment_commented_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='super_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='super_comments', to='blog.comment'),
        ),
    ]
