# Generated by Django 4.2.14 on 2024-12-21 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_comment_updated_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commented_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
