# Generated by Django 4.2.14 on 2025-01-06 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_comment_updated_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmedia',
            name='media_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
