# Generated by Django 4.2.14 on 2025-01-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_codeblock_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codeblock',
            name='code',
        ),
        migrations.AddField(
            model_name='codeblock',
            name='javaScript_code',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='codeblock',
            name='python_code',
            field=models.TextField(default=''),
        ),
    ]
